urls:
  50l-boiler: https://knoblauchwiki.vercel.app/reference%20guides/50L-Warmwasserboiler/
  50L-boiler: https://knoblauchwiki.vercel.app/reference%20guides/50L-Warmwasserboiler/
  boiler: https://knoblauchwiki.vercel.app/reference%20guides/50L-Warmwasserboiler/
  coffee: https://knoblauchwiki.vercel.app/howtos/coffee/
  fett: https://knoblauchwiki.vercel.app/reference%20guides/Fettabscheider/
